name: Deploy manylinux docker image

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file pyOpenMS/manylinux/Dockerfile --tag openms-manylinux2014_x86_64:$(date +%s)
