name: Deploy manylinux docker image

on:
  workflow_dispatch:
  push:
    branches:        
      - master
      - 'release/**'

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Define tag name
        shell: bash
        run: |
            BRANCH=${{ steps.extract_branch.outputs.branch }}
            ## use latest to follow docker conventions
            if [[ "$BRANCH" == "master" ]]
            then 
              BRANCH="latest"
            fi
            ## Remove release/ from release branch name
            echo "##[set-output name=tag;]$(echo ${BRANCH#release/})"
        id: tag_name
      - name: Downcase REPO
        run: echo "##[set-output name=repo;]$(echo ${GITHUB_REPOSITORY,,})"
        id: downcase_repo
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: jpfeuffer
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          context: pyOpenMS/manylinux
          tags: |
            ghcr.io/openms/contrib_manylinux2014:${{ steps.tag_name.outputs.tag }}
            
